update psycopg2 module to psycopg2-binary
### pip command related psycoqg2 yields the following error:

``` shell 
pip install -r requirements.txt
```

> ERROR: Failed building wheel for psycopg2



Thus reflected the following change on the [requirements.txt](./requirements.txt) from "psycopg" module to "psycopg2-binary"

The module has the same functionality as psycopg2. [Stackoverflow link is attached for your further reference](https://stackoverflow.com/questions/5420789/how-to-install-psycopg2-with-pip-on-python)

### My Environment
- Mac OS 10.15.3 (Cattalina)
- Python Virtual Environment(pipenv), python version 3.7